name: Docker

on:
  workflow_call:

jobs:
  
  docker: 
    runs-on: ubuntu:latest
    environment: Docker
    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Downlaod a Build Artifact
      uses: actions/download-artifact@v4
      with:
        name: java-project

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ vars.DOCKER_HUB_USERNAME }}/java-api:${{ github.ref_name }}