name: Docker

on:
  workflow_call:

jobs:

  docker:
    runs-on: ubuntu-latest
    environment: Docker
    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Download a Build Artifact
      uses: actions/download-artifact@v4
      with:
        name: go-api
    
    - name: Login to Docker
      uses: docker/login-action@v3
      with:
        username: ${{ var.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    
    - name: Build and push Docker images
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: javahenriquedev/go-api:${{ github.ref_name }}